repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-yaml
        args:
          - --allow-multiple-documents
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        files: \.ts|js|json|yaml|md?$
        types: [file]
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.30.0
  #   hooks:
  #     - id: eslint
  #       files: \.ts?$
  #       types: [file]
