apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: ms-commerce
build:
  artifacts:
    - image: yahiaeltai/auth
      context: services/auth
      docker:
        dockerfile: Dockerfile.dev
    - image: yahiaeltai/cart
      context: services/cart
      docker:
        dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
      - infra/k8s-dev/*
