apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: ms-commerce
build:
  artifacts:
    - image: europe-west1-docker.pkg.dev/ms-commerce-368507/ms-commerce/auth
      context: auth
      docker:
        dockerfile: Dockerfile.dev
    - image: europe-west1-docker.pkg.dev/ms-commerce-368507/ms-commerce/cart
      context: cart
      docker:
        dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
      - infra/k8s-dev/*
