apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service-auth-required
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/auth-url: http://account-srv.default.svc.cluster.local:3000/api/account/authenticate
    nginx.ingress.kubernetes.io/auth-method: POST
    nginx.ingress.kubernetes.io/auth-response-headers: UserId,UserEmail
spec:
  rules:
    - host: ms-commerce.dev
      http:
        paths:
          - path: /api/account/?(.*)
            pathType: Prefix
            backend:
              service:
                name: account-srv
                port:
                  number: 3000
          - path: /api/([^/\s]+)/carts/?(.*)
            pathType: Prefix
            backend:
              service:
                name: cart-srv
                port:
                  number: 3001
          - path: /api/([^/\s]+)/products/?(.*)
            pathType: Prefix
            backend:
              service:
                name: product-srv
                port:
                  number: 3002
