apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-commerce-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: ms-commerce.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ms-account
                port:
                  number: 3000
