version: '3'

services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
