version: '3.9'

services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      # maps ports 5432 (default PostgreSQL port to the host port 5435)
      - '127.0.0.1:5435:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
