ARG NODE_VERSION="20.0.0"
ARG ALPINE_VERSION="3.16"

FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION}

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN corepack enable && corepack prepare --activate

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm exec prisma generate --schema=src/prisma/schema.prisma

EXPOSE 3001

CMD ["pnpm", "run", "dev"]
