version: 2.1
build:
  docker:
    - image: alpine:3.15
  steps:
    - run:
        name: The First Step
        command: |
          echo 'Hello World!'
          echo 'This is the delivery pipeline'
