version: 2.1

orbs:
  node: circleci/node@5.0.3
  gcp-cli: circleci/gcp-cli@3.0.0
  gcp-gcr: circleci/gcp-gcr@0.15.0
  shellcheck: circleci/shellcheck@3.1.2

parameters:
  trigger_cart:
    type: boolean
    default: false
  trigger_auth:
    type: boolean
    default: false
  trigger_infra:
    type: boolean
    default: false

executors:
  gcp-executor:
    docker:
      - image: cimg/gcp:2022.11
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
  node-executor:
    docker:
      - image: cimg/node:18.12.1

jobs:
  lint_typecheck_and_test:
    executor: node-executor
    parameters:
      app-dir:
        type: string
    steps:
      - checkout
      - run:
          name: Setup machine
          command: ./.circleci/install-libssl.sh
      - shellcheck/check:
          dir: ./.circleci
      - node/install-packages
      - run:
          name: lint all services
          command: npm run lint
      - node/install-packages:
          app-dir: ./services/<< parameters.app-dir >>
      - run:
          command: cd ./services/<< parameters.app-dir >> && npx prisma generate --schema=src/prisma/schema.prisma
          name: Generate Prisma client
      - run:
          command: cd ./services/<< parameters.app-dir >> && npm run typecheck
          name: Typecheck services/<< parameters.app-dir >>
      - setup_remote_docker
      - run:
          name: Starting Postgres database
          command: |
            cd ./services/<< parameters.app-dir >> && docker-compose up -d
            sleep 20
      - run:
          name: Deploying Prisma schema
          command: cd ./services/<< parameters.app-dir >> && prisma migrate deploy --schema=src/prisma/schema.prisma
      - run:
          command: cd ./services/<< parameters.app-dir >> && npm run test:ci
          name: Run tests ./services/<< parameters.app-dir >>
  deploy_service:
    executor: gcp-executor
    parameters:
      service:
        type: string
    steps:
      - checkout
      - gcp-cli/setup
      - run:
          name: Rollout new << parameters.service >> deployment
          command: ./.circleci/kubernetes.sh
          environment:
            OPERATION: rollout
            SERVICE_NAME: << parameters.service >>
  deploy_manifests:
    executor: gcp-executor
    steps:
      - checkout
      - gcp-cli/setup
      - run:
          name: Apply all k8s manifests
          command: ./.circleci/kubernetes.sh
          environment:
            OPERATION: apply

workflows:
  test_cart_branch:
    when:
      and:
        - not:
            matches:
              pattern: '^main$'
              value: << pipeline.git.branch >>
        - equal: [true, << pipeline.parameters.trigger_cart >>]
    jobs:
      - lint_typecheck_and_test:
          name: lint_typecheck_and_test_cart
          app-dir: cart
  test_auth_branch:
    when:
      and:
        - not:
            matches:
              pattern: '^main$'
              value: << pipeline.git.branch >>
        - equal: [true, << pipeline.parameters.trigger_auth >>]
    jobs:
      - lint_typecheck_and_test:
          name: lint_typecheck_and_test_auth
          app-dir: auth

  test_and_deploy_cart:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
        - equal: [true, << pipeline.parameters.trigger_cart >>]
    jobs:
      - lint_typecheck_and_test:
          name: lint_typecheck_and_test_cart
          app-dir: cart
      - gcp-gcr/build-and-push-image:
          name: build_and_publish_cart_image
          docker-context: ./services/cart
          image: $REPO_NAME/cart
          path: ./services/cart
          registry-url: $REGISTRY_URL
          requires:
            - lint_typecheck_and_test_cart
      - can_deploy_service:
          name: can_deploy_cart_service
          type: approval
          requires:
            - build_and_publish_cart_image
      - deploy_service:
          name: deploy_cart_service
          service: cart
          requires:
            - can_deploy_cart_service
      - can_deploy_manifests:
          type: approval
      - deploy_manifests:
          requires:
            - can_deploy_manifests
  test_and_deploy_auth:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
        - equal: [true, << pipeline.parameters.trigger_auth >>]
    jobs:
      - lint_typecheck_and_test:
          name: lint_typecheck_and_test_auth
          app-dir: auth
      - gcp-gcr/build-and-push-image:
          name: build_and_publish_auth_image
          docker-context: ./services/auth
          image: $REPO_NAME/auth
          path: ./services/auth
          registry-url: $REGISTRY_URL
          requires:
            - lint_typecheck_and_test_auth
      - can_deploy_service:
          name: can_deploy_auth_service
          type: approval
          requires:
            - build_and_publish_auth_image
      - deploy_service:
          name: deploy_auth_service
          service: auth
          requires:
            - can_deploy_auth_service
      - can_deploy_manifests:
          type: approval
      - deploy_manifests:
          requires:
            - can_deploy_manifests
  deploy_manifests_if_changed:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
        - equal: [true, << pipeline.parameters.trigger_infra >>]
    jobs:
      - can_deploy_manifests:
          type: approval
      - deploy_manifests:
          requires:
            - can_deploy_manifests
