apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ms-commerce-cart.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ms-commerce-cart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ms-commerce-cart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{  .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env: 
            {{- $chartName := .Chart.Name -}}
            {{- range $key, $val := .Values.secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $chartName }}-secret
                  key: {{ $key }}
              {{- end}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Values.postgresql.name | quote }}
          image: {{ .Values.postgresql.image | quote }}
          command:
            - "/cloud_sql_proxy"
            - {{ include "ms-commerce-cart.postgresql-instances" . }}
          securityContext:
            runAsNonRoot: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}