apiVersion: v1
kind: Service
metadata:
  name: {{ include "ms-commerce-cart.fullname" . }}
  labels: 
    {{- include "ms-commerce-cart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector: {{- include "ms-commerce-cart.selectorLabels" . | nindent 4 }}