version: '3'

services:
  product_db:
    image: postgres:15.2
    restart: always
    ports:
      - '5436:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
