ingress:
  host: mss-commerce.com
  name: ms-commerce-ingress
  # Auth service must stay as the first service
  # You can add more services below
  services:
    - name: ms-commerce-auth
      path: /api/auth/?(.*)
      port: 3000
      pathType: Prefix
    - name: ms-commerce-cart
      path: /api/carts/?(.*)
      port: 3001
      pathType: Prefix
