apiVersion: v1
kind: Service
metadata:
  name: {{ include "ms-commerce-auth.fullname" . }}
  labels: 
    {{- include "ms-commerce-auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector: {{- include "ms-commerce-auth.selectorLabels" . | nindent 4 }}
