apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ms-account.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ms-account.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
{{ toYaml .Values.rollingUpdateStrategy | indent 6 }}
  minReadySeconds: 5
  template:
    metadata:
      labels:
        {{- include "ms-account.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
            {{- $chartName := .Chart.Name -}}
            {{- range $key, $val := .Values.secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $chartName }}-secret
                  key: {{ $key }}
              {{- end}}
            - name: ROARR_LOG
              value: 'true'
          ports:
            {{- range $key, $val := .Values.service.ports }}
              - name: {{ $val.name }}
                containerPort: {{ $val.port }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /ready
              port: 9000
            # failureThreshold * periodSeconds + initialDelaySeconds (5 * 10 + 15 = 65 seconds) before the first probe  
            # Once the startup probe has succeeded once, the liveness probe takes over to provide 
            # a fast response to container deadlocks. If the startup probe never succeeds,
            # the container is killed after 65s and subject to the pod's restartPolicy.
            failureThreshold: 5
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /live
              port: 9000
            # kubelet should wait 5 seconds before performing the first probe
            initialDelaySeconds: 5
            # kubelet should perform a liveness probe every 10 seconds
            periodSeconds: 10
            timeoutSeconds: 5
