replicaCount: 1

image:
  repository: europe-west1-docker.pkg.dev/ms-commerce-auto-1/ms-commerce/auth
  pullPolicy: IfNotPresent
  tag: 'latest'

nameOverride: 'cart'

serviceAccount:
  name: 'ksa-cloud-sql-cart'
  annotations:
    iam.gke.io/gcp-service-account: gke-cloud-sql-service-account@ms-commerce-auto-1.iam.gserviceaccount.com

service:
  type: ClusterIP
  port: 3001
  targetPort: 3001

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 384Mi
  limits:
    memory: 384Mi
    cpu: 300m

postgresql:
  name: cloud-sql-proxy
  image: gcr.io/cloudsql-docker/gce-proxy:latest
  instance: ms-commerce-auto-1:europe-west1:ms-commerce=tcp:5432

# Secrets are encryped with Cloud KMS
secrets: {}
