apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-mongo-pvc
  labels:
    app: auth-mongo
spec:
  storageClassName: ssd-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
