apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      serviceAccountName: identity-service-account-ms-commerce
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: 'true'
      containers:
        - name: cart
          image: europe-west1-docker.pkg.dev/ms-commerce-368507/ms-commerce/cart
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              memory: 384Mi
              cpu: 300m
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-cart-secret
                  key: MONGO_URI
            - name: GCP_PROJECT_ID
              value: ms-commerce-368507
---
apiVersion: v1
kind: Service
metadata:
  name: cart-srv
spec:
  selector:
    app: cart
  ports:
    - name: cart
      protocol: TCP
      port: 3001
      targetPort: 3001
