apiVersion: v1
kind: Service
metadata:
  name: {{include "ms-cart.fullname" .}}
  labels: {{- include "ms-cart.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports: {{- toYaml .Values.service.ports | nindent 4}}
  selector: {{- include "ms-cart.selectorLabels" . | nindent 4}}
