name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ms-commerce
      - name: apply k8s manifests
        run: kubectl apply -f infra/k8s -f infra/k8s-prod
