name: deploy-ms-auth

on:
  push:
    branches:
      - main
    paths:
      - "ms-auth/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        run: cd ms-auth && docker build -t yahiaeltai/ms-auth .
      - name: login to docker hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: push image to docker hub
        run: docker push yahiaeltai/ms-auth
      - name: install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ms-commerce
      - name: rollout new auth service deployment
        run: kubectl rollout restart deployment ms-auth-depl
