name: tests-ms-auth

on:
  pull_request:
    paths:
      - "ms-auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ms-auth && npm install && npm run test:ci
